### ISSUE TITLE
Compile and run

### ISSUE THREAD

**Issue by ploth** [muhbaasu/haskell-db-fahrplan-cli#1]
Excuse me, what do I have to do to compile and run your program?

**Comment by forgetaboutit** [comment]
Hi,

assuming you have Stack installed (check out [the docs](https://docs.haskellstack.org/en/stable/README/), if you're not familiar with it yet), running

`stack install`

should be enough. It will download the dependencies, compile the code and copy the executable to your local bin path (you can find the path by executing `stack path --local-bin-path`). The executable's name is `haskell-db-fahrplan-cli`.

Feel free to get in touch should anything come up.
